### ISSUE TITLE
Variables with empty strings are shown as the number 0

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#139] opened 2019-04-15 09:49 UTC
When you assign an empty string to a variable (e.g. `vars.my_var = ''`) and then show this variable in (say) a `sketchpad`, it will be rendered as the number 0. The variable does behave as an empty string in some other respects (for example when concatenating another string to it in an `inline_javascript` item), so it appears to be at least in part a visualization issue.

**Comment by dschreij** [comment] 2019-04-16 13:59
The problem was caused by https://github.com/shyras/osweb/blob/1.3/src/js/osweb/classes/syntax.js#L120.
Apparently calling `toNumber` on an empty string converts it to 0.
This has been fixed by not evaluating empty strings (which is more efficient anyway, I suppose)

**Comment by smathot** [comment] 2019-07-02 14:10
``` javascript
vars.test = ''
vars.test += 'a'
console.log(vars.test)
```

Still outputs '0a'. I will look into this myself, and if I don't manage I'll assign it to you.

**Closed as completed** 2020-04-15 13:36 UTC
Labels: bug
