### ISSUE TITLE
Arrow keys cause window to scroll

### ISSUE THREAD

**Issue by smathot** [shyras/osweb#109] opened 2018-10-06 07:59 UTC
Even when the experiment window is much smaller than the browser window, scroll bars are visible (at least on Chrome). This is not such a big deal in itself, but these scroll bars are controlled by the arrow keys. As a result, if the arrow keys are used as response keys during the experiment (as they often are), then the window is subtly scrolling left and right all the time!

![image](https://user-images.githubusercontent.com/594936/46568977-44944580-c94e-11e8-9434-6616f5144807.png)

**Comment by dschreij** [comment] 2018-10-06 09:17
I noticed this one too. It only occurs with Jatos experiments, right? On the osweb.cogsci.nl it appears to work correctly. This should be easily fixed by adding `max-width: 100vw; max-height: 100vh` to the style declarations of the body, or osweb container.

**Comment by smathot** [comment] 2018-10-07 10:02
> It only occurs with Jatos experiments, right?

It also occurs when running the experiment standalone from the extension. However, it indeed doesn't occur when you launch an experiment through the web interface (osweb.cogsci.nl).

**Comment by dschreij** [comment] 2018-12-07 09:42
This issue was caused by styling errors in the html for JATOS and Standalone versions of opensesame-extension-osweb, and has been fixed there.

**Closed as completed by dschreij** 2018-12-07 09:42 UTC
Labels: bug
